import type { SkillGraph } from "../types.js";

export const ccssWriting9To12: SkillGraph = {
  id: "ccss-writing-9-12",
  title: "Writing - Grades 9-12",
  version: "1.0.0",
  source: "Common Core State Standards for English Language Arts, Writing 9-12",
  framework: "CCSS-ELA",
  subject: "writing" as unknown as "ela",
  gradeBand: "9",
  skills: [
    {
      id: "ccss-writing.9.W.1",
      title: "Write evidence-based arguments",
      description: "I can support a clear claim with relevant evidence and reasoning.",
      subject: "writing" as unknown as "ela",
      gradeBand: "9",
      frameworkRefs: [{ framework: "CCSS-ELA", code: "W.9-10.1" }],
      prerequisites: [],
    },
    {
      id: "ccss-writing.10.W.2",
      title: "Explain complex ideas",
      description: "I can organize and explain a complex topic clearly.",
      subject: "writing" as unknown as "ela",
      gradeBand: "10",
      frameworkRefs: [{ framework: "CCSS-ELA", code: "W.9-10.2" }],
      prerequisites: ["ccss-writing.9.W.1"],
    },
    {
      id: "ccss-writing.11.W.5",
      title: "Strengthen writing through revision",
      description: "I can revise structure, evidence, and style for a specific audience.",
      subject: "writing" as unknown as "ela",
      gradeBand: "11",
      frameworkRefs: [{ framework: "CCSS-ELA", code: "W.11-12.5" }],
      prerequisites: ["ccss-writing.10.W.2"],
    },
    {
      id: "ccss-writing.12.W.8",
      title: "Synthesize credible sources",
      description: "I can evaluate and synthesize credible sources without plagiarism.",
      subject: "writing" as unknown as "ela",
      gradeBand: "12",
      frameworkRefs: [{ framework: "CCSS-ELA", code: "W.11-12.8" }],
      prerequisites: ["ccss-writing.11.W.5"],
    },
  ],
};

export const ashaSpeech9To12: SkillGraph = {
  id: "asha-speech-9-12",
  title: "Speech and Language - Grades 9-12",
  version: "1.0.0",
  source: "ASHA school-age language and communication practice guidance",
  framework: "ASHA",
  subject: "speech",
  gradeBand: "9",
  skills: [
    {
      id: "asha.speech.9.audience",
      title: "Adapt communication for an audience",
      description: "I can adjust my words, tone, and detail for different audiences.",
      subject: "speech",
      gradeBand: "9",
      frameworkRefs: [{ framework: "ASHA", code: "Pragmatics-Audience" }],
      prerequisites: [],
    },
    {
      id: "asha.speech.10.discourse",
      title: "Organize extended explanations",
      description: "I can organize a clear explanation with connected ideas.",
      subject: "speech",
      gradeBand: "10",
      frameworkRefs: [{ framework: "ASHA", code: "Discourse-Organization" }],
      prerequisites: ["asha.speech.9.audience"],
    },
    {
      id: "asha.speech.11.self-advocacy",
      title: "Communicate support needs",
      description: "I can explain the communication supports that help me participate.",
      subject: "speech",
      gradeBand: "11",
      frameworkRefs: [{ framework: "ASHA", code: "Self-Advocacy" }],
      prerequisites: ["asha.speech.10.discourse"],
    },
    {
      id: "asha.speech.12.professional",
      title: "Use professional communication",
      description: "I can communicate clearly in interviews, meetings, and workplace settings.",
      subject: "speech",
      gradeBand: "12",
      frameworkRefs: [{ framework: "ASHA", code: "Transition-Communication" }],
      prerequisites: ["asha.speech.11.self-advocacy"],
    },
  ],
};

export const executiveFunctionK12: SkillGraph = {
  id: "cec-executive-function-k-12",
  title: "Executive Function - Grades K-12",
  version: "1.0.0",
  source: "CEC-aligned executive-function learning progression",
  framework: "CEC-LS",
  subject: "executive_function",
  gradeBand: "K",
  skills: [
    {
      id: "executive-function.K.sequence",
      title: "Follow a short sequence",
      description: "I can follow two steps in order.",
      subject: "executive_function",
      gradeBand: "K",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Sequence.K" }],
      prerequisites: [],
    },
    {
      id: "executive-function.1.organize",
      title: "Put materials away",
      description: "I can keep my learning materials in their assigned places.",
      subject: "executive_function",
      gradeBand: "1",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Organization.1" }],
      prerequisites: ["executive-function.K.sequence"],
    },
    {
      id: "executive-function.2.plan",
      title: "Plan before starting",
      description: "I can name the first step before I begin a task.",
      subject: "executive_function",
      gradeBand: "2",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Planning.2" }],
      prerequisites: ["executive-function.1.organize"],
    },
    {
      id: "executive-function.3.initiate",
      title: "Start a manageable step",
      description: "I can begin a task by choosing one manageable step.",
      subject: "executive_function",
      gradeBand: "3",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Initiation.3" }],
      prerequisites: ["executive-function.2.plan"],
    },
    {
      id: "executive-function.4.working-memory",
      title: "Track multi-step directions",
      description: "I can use a written or visual aid to follow several steps.",
      subject: "executive_function",
      gradeBand: "4",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.WorkingMemory.4" }],
      prerequisites: ["executive-function.3.initiate"],
    },
    {
      id: "executive-function.5.monitor",
      title: "Check progress",
      description: "I can pause and check whether my work matches the goal.",
      subject: "executive_function",
      gradeBand: "5",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Monitoring.5" }],
      prerequisites: ["executive-function.4.working-memory"],
    },
    {
      id: "executive-function.6.prioritize",
      title: "Prioritize tasks",
      description: "I can order tasks by urgency and effort.",
      subject: "executive_function",
      gradeBand: "6",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Prioritization.6" }],
      prerequisites: ["executive-function.5.monitor"],
    },
    {
      id: "executive-function.7.flexibility",
      title: "Adjust a plan",
      description: "I can revise a plan when conditions change.",
      subject: "executive_function",
      gradeBand: "7",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Flexibility.7" }],
      prerequisites: ["executive-function.6.prioritize"],
    },
    {
      id: "executive-function.8.long-term",
      title: "Plan a long-term project",
      description: "I can break a long project into milestones and deadlines.",
      subject: "executive_function",
      gradeBand: "8",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.LongTerm.8" }],
      prerequisites: ["executive-function.7.flexibility"],
    },
    {
      id: "executive-function.9.schedule",
      title: "Balance a weekly schedule",
      description: "I can balance school, rest, and responsibilities across a week.",
      subject: "executive_function",
      gradeBand: "9",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Schedule.9" }],
      prerequisites: ["executive-function.8.long-term"],
    },
    {
      id: "executive-function.10.strategies",
      title: "Evaluate learning strategies",
      description: "I can compare strategies and choose the one that works best for me.",
      subject: "executive_function",
      gradeBand: "10",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Strategies.10" }],
      prerequisites: ["executive-function.9.schedule"],
    },
    {
      id: "executive-function.11.independent",
      title: "Manage independent work",
      description: "I can monitor deadlines and ask for support before I fall behind.",
      subject: "executive_function",
      gradeBand: "11",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Independence.11" }],
      prerequisites: ["executive-function.10.strategies"],
    },
    {
      id: "executive-function.12.transition",
      title: "Use executive-function supports after graduation",
      description: "I can choose tools and routines for college, work, or training.",
      subject: "executive_function",
      gradeBand: "12",
      frameworkRefs: [{ framework: "CEC-LS", code: "EF.Transition.12" }],
      prerequisites: ["executive-function.11.independent"],
    },
  ],
};

export const cecLifeSkillsK5: SkillGraph = {
  id: "cec-life-skills-k-5",
  title: "Life Skills - Grades K-5",
  version: "1.0.0",
  source: "CEC-aligned daily living and safety progression",
  framework: "CEC-LS",
  subject: "life_skills",
  gradeBand: "K",
  skills: ["K", "1", "2", "3", "4", "5"].map((grade, index) => ({
    id: `life-skills.${grade}.independence`,
    title: ["Follow a daily routine", "Practice personal safety", "Use time and money", "Prepare simple food", "Plan a small budget", "Manage household tasks"][index],
    description: ["I can follow a familiar daily routine.", "I can make a safe choice and find a trusted adult.", "I can use simple time and money skills.", "I can prepare a simple snack safely.", "I can plan how to use a small amount of money.", "I can complete a household task using a checklist."][index],
    subject: "life_skills" as const,
    gradeBand: grade as "K" | "1" | "2" | "3" | "4" | "5",
    frameworkRefs: [{ framework: "CEC-LS" as const, code: `DailyLiving.${grade}` }],
    prerequisites: index === 0 ? [] : [`life-skills.${["K", "1", "2", "3", "4"][index - 1]}.independence`],
  })),
};

export const actflWorldLanguagesK5: SkillGraph = {
  id: "actfl-world-languages-k-5",
  title: "World Languages - Grades K-5",
  version: "1.0.0",
  source: "ACTFL World-Readiness Standards, novice learner progression",
  framework: "ACTFL",
  subject: "world_languages",
  gradeBand: "K",
  skills: ["K", "1", "2", "3", "4", "5"].map((grade, index) => ({
    id: `actfl.world-languages.${grade}.communication`,
    title: ["Recognize greetings", "Exchange names", "Identify familiar words", "Ask a simple question", "Describe familiar things", "Understand a short message"][index],
    description: ["I can recognize and use a greeting.", "I can say my name and ask someone else's name.", "I can identify familiar words and pictures.", "I can ask and answer a simple practiced question.", "I can describe familiar people, places, or things.", "I can understand the main idea of a short familiar message."][index],
    subject: "world_languages" as const,
    gradeBand: grade as "K" | "1" | "2" | "3" | "4" | "5",
    frameworkRefs: [{ framework: "ACTFL" as const, code: `Communication.${grade}` }],
    prerequisites: index === 0 ? [] : [`actfl.world-languages.${["K", "1", "2", "3", "4"][index - 1]}.communication`],
  })),
};

export const ncasMusic9To12: SkillGraph = {
  id: "ncas-music-9-12",
  title: "Music - Grades 9-12",
  version: "1.0.0",
  source: "National Core Arts Standards, Music",
  framework: "NCAS",
  subject: "music",
  gradeBand: "9",
  skills: ["9", "10", "11", "12"].map((grade, index) => ({
    id: `ncas.music.${grade}.create-perform-respond`,
    title: ["Develop a musical idea", "Refine a performance", "Analyze musical choices", "Present an artistic portfolio"][index],
    description: ["I can develop a musical idea using rhythm, melody, or harmony.", "I can rehearse and refine a performance using feedback.", "I can analyze how musical choices create meaning.", "I can present and explain a portfolio of musical work."][index],
    subject: "music" as const,
    gradeBand: grade as "9" | "10" | "11" | "12",
    frameworkRefs: [{ framework: "NCAS" as const, code: `Music.${grade}` }],
    prerequisites: index === 0 ? [] : [`ncas.music.${["9", "10", "11"][index - 1]}.create-perform-respond`],
  })),
};

export const ngssEngineeringK2: SkillGraph = {
  id: "ngss-engineering-design-k-2",
  title: "Engineering Design - Grades K-2",
  version: "1.0.0",
  source: "Next Generation Science Standards K-2-ETS1",
  framework: "NGSS-Engineering",
  subject: "stem_engineering",
  gradeBand: "K",
  skills: ["K", "1", "2"].map((grade, index) => ({
    id: `ngss.engineering.${grade}.ETS1`,
    title: ["Ask about a problem", "Sketch a solution", "Compare test results"][index],
    description: ["I can ask what a design needs to do.", "I can draw a possible solution.", "I can compare tests and choose an improvement."][index],
    subject: "stem_engineering" as const,
    gradeBand: grade as "K" | "1" | "2",
    frameworkRefs: [{ framework: "NGSS-Engineering" as const, code: `K-2-ETS1-${index + 1}` }],
    prerequisites: index === 0 ? [] : [`ngss.engineering.${["K", "1"][index - 1]}.ETS1`],
  })),
};
