// "Inclusive Lab — Warm" preset.
//
// This is the approved AIVO platform-wide design language (May 2026).
// Source of truth for the rollout described in
// `.local/inclusive-warm-rollout-plan.md`.
//
// The visual spec lives in
// `artifacts/mockup-sandbox/src/components/mockups/aivo-inclusive-warm/`.
//
// Consumers:
//   - `apps/marketing`   imports `@aivo/brand/tokens.css` and `INCLUSIVE_WARM`
//   - `apps/web-v2`      imports `@aivo/brand/tokens.css` and `INCLUSIVE_WARM`
//   - `apps/mobile`      imports `INCLUSIVE_WARM` directly (no CSS variables on RN)
//
// The CSS layer of this preset is generated by
// `packages/brand/scripts/build-tokens.mjs` from the JSON tokens in
// `tokens/core/*.json`, `tokens/semantic/*.json`, and
// `tokens/modes/sensory.json`. Do not duplicate those values here.

export type SensoryMode = "standard" | "calm" | "high-contrast";

export const SENSORY_MODES: readonly SensoryMode[] = [
  "standard",
  "calm",
  "high-contrast",
] as const;

/** Lookup label and helper text for the in-product sensory mode toggle. */
export const SENSORY_MODE_LABELS: Record<
  SensoryMode,
  { label: string; description: string }
> = {
  standard: {
    label: "Standard",
    description: "Full brand palette and motion.",
  },
  calm: {
    label: "Calm",
    description: "Lower saturation, softer shadows, reduced motion.",
  },
  "high-contrast": {
    label: "High Contrast",
    description: "Maximum contrast and no motion. WCAG AAA targets.",
  },
};

/**
 * Resolves an arbitrary string into a known SensoryMode.
 * Mirrors the pattern of `resolveTheme()` / `resolveAgeMode()` in
 * `./playful-calm.ts`.
 */
export function resolveSensoryMode(
  mode: string | null | undefined,
): SensoryMode {
  if (mode === "standard" || mode === "calm" || mode === "high-contrast") {
    return mode;
  }
  return "standard";
}

/**
 * Returns the `data-*` attribute set to apply to `<html>` so the
 * CSS variable overrides emitted by `build-tokens.mjs` take effect.
 */
export function getInclusiveWarmDataset(input: {
  sensoryMode?: string | null;
  dyslexiaFont?: boolean | null;
}): Record<string, string> {
  const attrs: Record<string, string> = {
    "data-sensory-mode": resolveSensoryMode(input.sensoryMode),
    "data-brand": "inclusive-warm",
  };
  if (input.dyslexiaFont) {
    attrs["data-dyslexia-font"] = "on";
  }
  return attrs;
}

/**
 * Named color families that compose the Inclusive Warm identity.
 * Use these when you need a palette ramp (e.g. building a chart
 * legend, a status pill grid). For semantic intent, prefer
 * `INCLUSIVE_WARM_PALETTE` below.
 */
export const CALM_SKY = {
  50: "#eff6ff",
  100: "#dbeafe",
  200: "#bfdbfe",
  300: "#93c5fd",
  400: "#60a5fa",
  500: "#3b82f6",
  600: "#2563eb",
  700: "#1d4ed8",
  800: "#1e40af",
  900: "#1e3a8a",
} as const;

export const LAVENDER = {
  50: "#f5f3ff",
  100: "#ede9fe",
  200: "#ddd6fe",
  300: "#c4b5fd",
  400: "#a78bfa",
  500: "#8b5cf6",
  600: "#7c3aed",
  700: "#6d28d9",
  800: "#5b21b6",
  900: "#4c1d95",
} as const;

export const SUNSHINE = {
  50: "#fffbeb",
  100: "#fef3c7",
  200: "#fde68a",
  300: "#fcd34d",
  400: "#fbbf24",
  500: "#f59e0b",
  600: "#d97706",
  700: "#b45309",
  800: "#92400e",
  900: "#78350f",
} as const;

/**
 * Palette anchor colors. These are intentionally a small,
 * named subset of the ramps above —
 * just the colors a consumer needs to reference by name when
 * CSS variables aren't available (React Native, inline SVGs,
 * email templates).
 */
export const INCLUSIVE_WARM_PALETTE = {
  primary: "#3b82f6",
  primaryHover: "#2563eb",
  primaryDeep: "#1d4ed8",
  primarySoft: "#dbeafe",
  primaryFg: "#ffffff",

  accent: "#a78bfa",
  accentDeep: "#7c3aed",
  accentSoft: "#ede9fe",

  warm: "#f59e0b",
  warmDeep: "#b45309",
  warmSoft: "#fef3c7",

  bgPage: "#f5f3ff",
  bgCard: "#fdfaf3",
  bgRaised: "#ffffff",

  ink: "#111827",
  inkMuted: "#4b5563",
  inkSubtle: "#6b7280",

  border: "#e5e7eb",
  borderStrong: "#d1d5db",

  // Wordmark gradient ends. Used for hero word-highlight, brand chip,
  // any inline SVG that needs to match the logo.
  gradientStart: "#3b82f6",
  gradientEnd: "#a78bfa",
} as const;

export type InclusiveWarmColor = keyof typeof INCLUSIVE_WARM_PALETTE;

export const INCLUSIVE_WARM_GRADIENTS = {
  // `brand` is the identity gradient (logo SVG fills, email templates,
  // PNG exports). It does NOT respond to sensory mode — the logo
  // shouldn't recolor itself.
  brand: `linear-gradient(135deg, ${INCLUSIVE_WARM_PALETTE.gradientStart} 0%, ${INCLUSIVE_WARM_PALETTE.gradientEnd} 100%)`,
  // `sensoryBrand` is the in-product gradient (headline word highlight,
  // hero accents). It uses CSS vars so it shifts in calm /
  // high-contrast modes to stay WCAG-compliant.
  sensoryBrand: `linear-gradient(135deg, var(--aivo-sensory-primary) 0%, var(--aivo-sensory-accent) 100%)`,
  hero: `linear-gradient(180deg, var(--aivo-sensory-bgPage) 0%, var(--aivo-sensory-bgRaised) 70%)`,
  warmHighlight: `linear-gradient(180deg, transparent 55%, var(--aivo-sensory-accentSoft) 55%)`,
} as const;

export const INCLUSIVE_WARM_RADII = {
  pill: "9999px",
  control: "9999px",
  card: "1.5rem",
  cardLarge: "2rem",
  hero: "2.5rem",
} as const;

export const INCLUSIVE_WARM_FONTS = {
  display: "'Fredoka', 'Nunito', ui-sans-serif, system-ui, sans-serif",
  body: "'Nunito', ui-sans-serif, system-ui, sans-serif",
  mono: "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace",
  dyslexia: "'OpenDyslexic', 'Comic Sans MS', 'Arial', sans-serif",
} as const;

/**
 * Tailwind class-name recipes for the core component vocabulary.
 * Web and web-v2 should compose these (rather than redefine them)
 * so the design system stays consistent.
 *
 * These are intentionally Tailwind strings (not styled-components):
 *   - keeps the package tooling-free
 *   - shadcn primitives in `apps/web-v2` consume them via `cn(...)`
 *   - the marketing site composes them with `clsx(...)`
 */
export const INCLUSIVE_WARM_RECIPES = {
  buttonPrimary:
    "inline-flex items-center justify-center gap-2 h-12 px-7 rounded-full text-base font-semibold bg-[var(--aivo-sensory-primary)] text-[var(--aivo-sensory-primaryFg)] shadow-md shadow-[color-mix(in_oklab,var(--aivo-sensory-primary)_25%,transparent)] hover:bg-[var(--aivo-sensory-primaryHover)] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--aivo-sensory-ringFocus)] focus-visible:ring-offset-2 disabled:opacity-50",
  buttonGhost:
    "inline-flex items-center justify-center gap-2 h-12 px-7 rounded-full text-base font-semibold text-[var(--aivo-sensory-primary)] bg-[color-mix(in_oklab,var(--aivo-sensory-bgRaised)_70%,transparent)] hover:bg-[var(--aivo-sensory-bgRaised)] border border-[var(--aivo-sensory-border)] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--aivo-sensory-ringFocus)] focus-visible:ring-offset-2",
  cardSoft:
    "rounded-[1.5rem] border border-[var(--aivo-sensory-border)] bg-[var(--aivo-sensory-bgCard)] shadow-sm",
  cardHero:
    "rounded-[2.5rem] border border-white/40 bg-[var(--aivo-sensory-bgRaised)] shadow-xl shadow-[color-mix(in_oklab,var(--aivo-sensory-accent)_15%,transparent)]",
  sensoryToggleWrap:
    "inline-flex items-center gap-1 p-1 rounded-full bg-[color-mix(in_oklab,var(--aivo-sensory-bgRaised)_60%,transparent)] border border-[var(--aivo-sensory-border)] shadow-sm",
  sensoryToggleItem:
    "px-3 h-8 inline-flex items-center rounded-full text-xs font-semibold text-[var(--aivo-sensory-inkMuted)] hover:text-[var(--aivo-sensory-ink)] transition-colors",
  sensoryToggleItemActive:
    "bg-[var(--aivo-sensory-bgRaised)] text-[var(--aivo-sensory-ink)] shadow-sm",
  navCapsuleDark:
    "flex items-center justify-around bg-[#1a1c23] rounded-full h-16 px-2 shadow-2xl",
  navCapsuleItem:
    "flex-1 inline-flex flex-col items-center gap-1 h-full justify-center text-white/55 hover:text-white text-[10px] font-bold transition-colors",
  navCapsuleItemActive:
    "text-[var(--aivo-sensory-warm)] [&_svg]:fill-current/10",
  headlineDisplay:
    "font-display font-bold tracking-tight leading-[1.05] text-[var(--aivo-sensory-ink)]",
  // Uses sensory-mode CSS vars so high-contrast mode collapses the
  // gradient to solid ink (passes WCAG AAA), and calm mode shifts to
  // the slightly deeper blue/lavender pair.
  headlineGradientWord:
    "bg-clip-text text-transparent bg-[linear-gradient(135deg,var(--aivo-sensory-primary)_0%,var(--aivo-sensory-accent)_100%)]",
  bodyText: "font-body text-[var(--aivo-sensory-inkMuted)] leading-relaxed",
  badgeSoft:
    "inline-flex items-center gap-1.5 px-3 h-7 rounded-full text-xs font-semibold bg-[var(--aivo-sensory-accentSoft)] text-[var(--aivo-sensory-accentDeep,var(--aivo-sensory-accent))]",
  surfacePage:
    "bg-[var(--aivo-sensory-bgPage)] text-[var(--aivo-sensory-ink)] font-body",
} as const;

/**
 * Canonical CSS variable names emitted by `build-tokens.mjs` from
 * `tokens/modes/sensory.json`. Listed here so React Native consumers
 * (which can't read CSS) can write a JS shim that mirrors the same
 * names.
 *
 * Pattern: `--aivo-sensory-<key>`
 */
export const INCLUSIVE_WARM_CSS_VARS = {
  bgPage: "--aivo-sensory-bgPage",
  bgCard: "--aivo-sensory-bgCard",
  bgRaised: "--aivo-sensory-bgRaised",
  primary: "--aivo-sensory-primary",
  primaryHover: "--aivo-sensory-primaryHover",
  primaryFg: "--aivo-sensory-primaryFg",
  accent: "--aivo-sensory-accent",
  accentSoft: "--aivo-sensory-accentSoft",
  warm: "--aivo-sensory-warm",
  warmSoft: "--aivo-sensory-warmSoft",
  ink: "--aivo-sensory-ink",
  inkMuted: "--aivo-sensory-inkMuted",
  border: "--aivo-sensory-border",
  ringFocus: "--aivo-sensory-ringFocus",
  motionScale: "--aivo-sensory-motionScale",
  shadowStrength: "--aivo-sensory-shadowStrength",
} as const;

/** Resolved palette per sensory mode. Mirrors the JSON tokens; used by
 *  React Native (which can't read CSS variables) and by any code that
 *  needs a fully-resolved color value at build time (emails, images).
 */
export const INCLUSIVE_WARM_BY_MODE: Record<
  SensoryMode,
  {
    bgPage: string;
    bgCard: string;
    bgRaised: string;
    primary: string;
    primaryHover: string;
    primaryFg: string;
    accent: string;
    accentSoft: string;
    warm: string;
    warmSoft: string;
    ink: string;
    inkMuted: string;
    border: string;
    ringFocus: string;
    motionScale: number;
    shadowStrength: number;
  }
> = {
  standard: {
    bgPage: "#f5f3ff",
    bgCard: "#fdfaf3",
    bgRaised: "#ffffff",
    primary: "#3b82f6",
    primaryHover: "#2563eb",
    primaryFg: "#ffffff",
    accent: "#a78bfa",
    accentSoft: "#ede9fe",
    warm: "#f59e0b",
    warmSoft: "#fef3c7",
    ink: "#111827",
    inkMuted: "#4b5563",
    border: "#e5e7eb",
    ringFocus: "#3b82f6",
    motionScale: 1,
    shadowStrength: 0.14,
  },
  calm: {
    bgPage: "#f3f1ec",
    bgCard: "#fefdf9",
    bgRaised: "#ffffff",
    primary: "#2563eb",
    primaryHover: "#1d4ed8",
    primaryFg: "#ffffff",
    accent: "#8b5cf6",
    accentSoft: "#ede9fe",
    warm: "#b45309",
    warmSoft: "#fef3c7",
    ink: "#1f2937",
    inkMuted: "#52525b",
    border: "#d6d3d1",
    ringFocus: "#2563eb",
    motionScale: 0.5,
    shadowStrength: 0.08,
  },
  "high-contrast": {
    bgPage: "#ffffff",
    bgCard: "#ffffff",
    bgRaised: "#ffffff",
    primary: "#1d4ed8",
    primaryHover: "#1e3a8a",
    primaryFg: "#ffffff",
    accent: "#5b21b6",
    accentSoft: "#e5e7eb",
    warm: "#92400e",
    warmSoft: "#f3f4f6",
    ink: "#000000",
    inkMuted: "#1f2937",
    border: "#000000",
    ringFocus: "#000000",
    motionScale: 0,
    shadowStrength: 0,
  },
};

/** Default brand identity (logo variants + wordmark). Source files live
 *  in `apps/marketing/public/images/`; canonical names mirrored from
 *  `./assets.ts`. */
export const INCLUSIVE_WARM_LOGOS = {
  purple: "/images/aivo-logo-purple.png",
  dark: "/images/aivo-logo-dark.png",
  white: "/images/aivo-logo-white.png",
} as const;

export const INCLUSIVE_WARM = {
  brandKey: "inclusive-warm" as const,
  modes: SENSORY_MODES,
  modeLabels: SENSORY_MODE_LABELS,
  palette: INCLUSIVE_WARM_PALETTE,
  paletteByMode: INCLUSIVE_WARM_BY_MODE,
  ramps: { calmSky: CALM_SKY, lavender: LAVENDER, sunshine: SUNSHINE },
  gradients: INCLUSIVE_WARM_GRADIENTS,
  radii: INCLUSIVE_WARM_RADII,
  fonts: INCLUSIVE_WARM_FONTS,
  recipes: INCLUSIVE_WARM_RECIPES,
  cssVars: INCLUSIVE_WARM_CSS_VARS,
  logos: INCLUSIVE_WARM_LOGOS,
  resolveSensoryMode,
  getDataset: getInclusiveWarmDataset,
} as const;

export type InclusiveWarmPreset = typeof INCLUSIVE_WARM;
