-- Phase 2 — calendar-driven weekly pacing.
--
-- A learner's district/grade scope-&-sequence (generated by brain-svc) is
-- exploded into a dated, week-by-week plan aligned to a school calendar so the
-- tutor serves the right topics each week and pauses instruction over breaks.
-- brain-svc reads/writes these tables via raw SQL.

CREATE TABLE IF NOT EXISTS "school_calendars" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" UUID NOT NULL REFERENCES "tenants"("id"),
  "learner_id" UUID NOT NULL REFERENCES "learners"("id") ON DELETE CASCADE,
  "district_id" UUID,
  "name" VARCHAR(255),
  "academic_year" VARCHAR(16),
  "timezone" VARCHAR(64) NOT NULL DEFAULT 'America/Chicago',
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "school_calendars_learner_id_idx" ON "school_calendars" ("learner_id");
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "school_calendar_terms" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "calendar_id" UUID NOT NULL REFERENCES "school_calendars"("id") ON DELETE CASCADE,
  "term_number" INTEGER NOT NULL,
  "title" VARCHAR(255),
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "school_calendar_terms_calendar_id_idx" ON "school_calendar_terms" ("calendar_id");
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "school_calendar_breaks" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "calendar_id" UUID NOT NULL REFERENCES "school_calendars"("id") ON DELETE CASCADE,
  "kind" VARCHAR(16) NOT NULL DEFAULT 'break',
  "name" VARCHAR(255),
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "school_calendar_breaks_calendar_id_idx" ON "school_calendar_breaks" ("calendar_id");
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "learner_pacing_plans" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" UUID NOT NULL REFERENCES "tenants"("id"),
  "learner_id" UUID NOT NULL REFERENCES "learners"("id") ON DELETE CASCADE,
  "calendar_id" UUID REFERENCES "school_calendars"("id") ON DELETE SET NULL,
  "subject" VARCHAR(64) NOT NULL,
  "framework" VARCHAR(128),
  "grade_level" VARCHAR(16),
  "status" VARCHAR(16) NOT NULL DEFAULT 'active',
  "plan_start" DATE NOT NULL,
  "source_scope_sequence" JSONB DEFAULT '{}'::jsonb,
  "pacing_rationale" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "learner_pacing_plans_learner_id_idx" ON "learner_pacing_plans" ("learner_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "learner_pacing_plans_subject_idx" ON "learner_pacing_plans" ("subject");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "learner_pacing_plans_status_idx" ON "learner_pacing_plans" ("status");
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "learner_pacing_weeks" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "pacing_plan_id" UUID NOT NULL REFERENCES "learner_pacing_plans"("id") ON DELETE CASCADE,
  "week_index" INTEGER NOT NULL,
  "week_start" DATE NOT NULL,
  "week_end" DATE NOT NULL,
  "kind" VARCHAR(16) NOT NULL DEFAULT 'instruction',
  "term_number" INTEGER,
  "unit_title" VARCHAR(255),
  "topics" JSONB DEFAULT '[]'::jsonb,
  "standards" JSONB DEFAULT '[]'::jsonb,
  "objectives" JSONB DEFAULT '[]'::jsonb,
  "vocabulary" JSONB DEFAULT '[]'::jsonb,
  "status" VARCHAR(16) NOT NULL DEFAULT 'planned',
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "learner_pacing_weeks_plan_id_idx" ON "learner_pacing_weeks" ("pacing_plan_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "learner_pacing_weeks_week_start_idx" ON "learner_pacing_weeks" ("week_start");
