-- 0082_web_clinical.sql
--
-- Sprint 3 (persistence migration): the web-owned IEP AI-draft review inbox.
-- ADR 0015 — canonical clinical records (IEP goals, therapist notes,
-- caregiver observations) stay in services/family-svc (write-through over
-- REST). This is the one clinical artifact web-v2 owns: an AI-generated IEP
-- draft per learner moving through a review lifecycle (ai_draft →
-- teacher_review → admin_approved → active → archived), regenerated by upsert.
--
-- Tenant-scoped + RLS (single-tenant access by the reviewing teacher/admin,
-- same model as web_iep_documents in 0050). The aivo_app role is granted via
-- 0050's ALTER DEFAULT PRIVILEGES; withTenantContext sets app.current_tenant.
--
-- See packages/db/src/schema/web-clinical.ts for the drizzle definition.

CREATE TABLE IF NOT EXISTS "web_iep_ai_drafts" (
  "id" text PRIMARY KEY NOT NULL,
  "learner_id" text NOT NULL,
  "tenant_id" text NOT NULL,
  "updated_at" text NOT NULL,
  "data" jsonb NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "web_iep_ai_drafts_idx"
  ON "web_iep_ai_drafts" ("tenant_id", "learner_id");
--> statement-breakpoint

ALTER TABLE "web_iep_ai_drafts" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DROP POLICY IF EXISTS "tenant_isolation" ON "web_iep_ai_drafts";
--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "web_iep_ai_drafts"
  USING (tenant_id = current_setting('app.current_tenant', true))
  WITH CHECK (tenant_id = current_setting('app.current_tenant', true));
