import type { Item } from "../../services/types.js";

/**
 * 30 social-studies fixture items spanning civics, geography, history,
 * and economics across K-8. Surfaces mix text (`choice_grid`), video
 * (`video` with caption URLs — captions are required at ingest), and
 * the map workspace.
 */
export const SOCIAL_STUDIES_ITEMS: Item[] = [
  // Civics (8)
  {
    id: "SS.IT.CIV.001",
    skillCode: "SS.CIV.RULES_K2",
    difficulty: -1.5,
    surface: "choice_grid",
    prompt: "Why do classrooms have rules?",
    options: ["To keep everyone safe and fair", "To make people sad", "To waste time", "For decoration"],
  },
  {
    id: "SS.IT.CIV.002",
    skillCode: "SS.CIV.GOV_3_5",
    difficulty: 0.0,
    surface: "choice_grid",
    prompt: "Which branch of the U.S. government makes laws?",
    options: ["Legislative", "Executive", "Judicial", "Military"],
  },
  {
    id: "SS.IT.CIV.003",
    skillCode: "SS.CIV.CONST_6_8",
    difficulty: 0.8,
    surface: "choice_grid",
    prompt: "The Bill of Rights is which part of the Constitution?",
    options: ["The first ten amendments", "The preamble", "Article I", "The signatures page"],
  },
  {
    id: "SS.IT.CIV.004",
    skillCode: "SS.CIV.CITIZEN",
    difficulty: 0.2,
    surface: "choice_grid",
    prompt: "Which is a responsibility of citizens?",
    options: ["Voting and following the law", "Designing the flag", "Naming the seasons", "Choosing the weather"],
  },
  {
    id: "SS.IT.CIV.005",
    skillCode: "SS.CIV.LOCAL_GOV",
    difficulty: -0.3,
    surface: "choice_grid",
    prompt: "Who leads a city's local government?",
    options: ["Mayor", "President", "Governor", "Senator"],
  },
  {
    id: "SS.IT.CIV.006",
    skillCode: "SS.CIV.STATE_GOV",
    difficulty: 0.3,
    surface: "choice_grid",
    prompt: "Who is the head of a state government?",
    options: ["Governor", "Mayor", "President", "Chief Justice"],
  },
  {
    id: "SS.IT.CIV.007",
    skillCode: "SS.CIV.FED_GOV",
    difficulty: 0.7,
    surface: "video",
    prompt: "Watch the clip on the three branches. Which checks the President's power?",
    mediaUrl: "https://media.aivo.dev/ss/three-branches.mp4",
    captionUrl: "https://media.aivo.dev/ss/three-branches.vtt",
    options: ["Congress", "The Cabinet", "The Press", "The States"],
  },
  {
    id: "SS.IT.CIV.008",
    skillCode: "SS.CIV.LAW",
    difficulty: 0.5,
    surface: "choice_grid",
    prompt: "Who decides if a law has been broken in a courtroom?",
    options: ["A judge or jury", "The mayor", "Voters", "The principal"],
  },

  // Geography (8)
  {
    id: "SS.IT.GEO.001",
    skillCode: "SS.GEO.MAPS_K2",
    difficulty: -1.5,
    surface: "choice_grid",
    prompt: "Which direction is at the top of most maps?",
    options: ["North", "South", "East", "West"],
  },
  {
    id: "SS.IT.GEO.002",
    skillCode: "SS.GEO.REGIONS_3_5",
    difficulty: -0.5,
    surface: "choice_grid",
    prompt: "How many continents are there?",
    options: ["Seven", "Five", "Nine", "Three"],
  },
  {
    id: "SS.IT.GEO.003",
    skillCode: "SS.GEO.PHYSICAL_6_8",
    difficulty: 0.8,
    surface: "choice_grid",
    prompt: "Which biome has the most rainfall per year?",
    options: ["Tropical rainforest", "Tundra", "Desert", "Grassland"],
  },
  {
    id: "SS.IT.GEO.004",
    skillCode: "SS.GEO.HUMAN",
    difficulty: 0.4,
    surface: "video",
    prompt: "Watch the migration clip. What is one common reason people migrate?",
    mediaUrl: "https://media.aivo.dev/ss/migration.mp4",
    captionUrl: "https://media.aivo.dev/ss/migration.vtt",
    options: ["Looking for better opportunities", "To repaint their homes", "To rename rivers", "For no reason"],
  },
  {
    id: "SS.IT.GEO.005",
    skillCode: "SS.GEO.US_STATES",
    difficulty: 0.0,
    surface: "choice_grid",
    prompt: "What is the capital of California?",
    options: ["Sacramento", "Los Angeles", "San Francisco", "San Diego"],
  },
  {
    id: "SS.IT.GEO.006",
    skillCode: "SS.GEO.WORLD_COUNTRIES",
    difficulty: 0.6,
    surface: "choice_grid",
    prompt: "Which country has the most people?",
    options: ["India", "United States", "Brazil", "Russia"],
  },
  {
    id: "SS.IT.GEO.007",
    skillCode: "SS.GEO.ENVIRONMENT",
    difficulty: 0.5,
    surface: "choice_grid",
    prompt: "Which is a renewable resource?",
    options: ["Sunlight", "Coal", "Natural gas", "Oil"],
  },
  {
    id: "SS.IT.GEO.008",
    skillCode: "SS.GEO.MAPS_K2",
    difficulty: -0.8,
    surface: "choice_grid",
    prompt: "A map key tells you…",
    options: ["What the symbols mean", "Who made the map", "When it was printed", "How heavy it is"],
  },

  // History (8)
  {
    id: "SS.IT.HIST.001",
    skillCode: "SS.HIST.TIME_K2",
    difficulty: -1.5,
    surface: "choice_grid",
    prompt: "Which happened first?",
    options: ["You were born", "You started school", "You started reading", "You learned your name"],
  },
  {
    id: "SS.IT.HIST.002",
    skillCode: "SS.HIST.NATIVE",
    difficulty: -0.5,
    surface: "choice_grid",
    prompt: "Who lived in the Americas before European arrival?",
    options: ["Indigenous / Native peoples", "Vikings only", "No one", "Romans"],
  },
  {
    id: "SS.IT.HIST.003",
    skillCode: "SS.HIST.COLONIAL",
    difficulty: 0.0,
    surface: "choice_grid",
    prompt: "The 13 colonies were located on which coast?",
    options: ["Atlantic (east)", "Pacific (west)", "Gulf (south)", "Arctic (north)"],
  },
  {
    id: "SS.IT.HIST.004",
    skillCode: "SS.HIST.REVOLUTION",
    difficulty: 0.4,
    surface: "video",
    prompt: "Watch the Declaration clip. In what year was the Declaration of Independence signed?",
    mediaUrl: "https://media.aivo.dev/ss/declaration.mp4",
    captionUrl: "https://media.aivo.dev/ss/declaration.vtt",
    options: ["1776", "1492", "1812", "1865"],
  },
  {
    id: "SS.IT.HIST.005",
    skillCode: "SS.HIST.CIVIL_WAR",
    difficulty: 0.6,
    surface: "choice_grid",
    prompt: "What was one main cause of the U.S. Civil War?",
    options: ["Disagreement over slavery", "A bad harvest", "A spelling reform", "A scientific discovery"],
  },
  {
    id: "SS.IT.HIST.006",
    skillCode: "SS.HIST.CIVIL_RIGHTS",
    difficulty: 0.7,
    surface: "video",
    prompt: "Watch the March on Washington clip. Who delivered the 'I Have a Dream' speech?",
    mediaUrl: "https://media.aivo.dev/ss/mlk.mp4",
    captionUrl: "https://media.aivo.dev/ss/mlk.vtt",
    options: ["Martin Luther King Jr.", "Rosa Parks", "Malcolm X", "Frederick Douglass"],
  },
  {
    id: "SS.IT.HIST.007",
    skillCode: "SS.HIST.WORLD_ANCIENT",
    difficulty: 0.5,
    surface: "choice_grid",
    prompt: "The pyramids of Giza were built in which ancient civilization?",
    options: ["Egypt", "Greece", "Rome", "China"],
  },
  {
    id: "SS.IT.HIST.008",
    skillCode: "SS.HIST.EXPLORATION",
    difficulty: 0.5,
    surface: "choice_grid",
    prompt: "Which explorer is associated with the 1492 voyage?",
    options: ["Christopher Columbus", "Magellan", "Marco Polo", "Vasco da Gama"],
  },

  // Economics (6)
  {
    id: "SS.IT.ECON.001",
    skillCode: "SS.ECON.NEEDS_K2",
    difficulty: -1.5,
    surface: "choice_grid",
    prompt: "Which is a need?",
    options: ["Water", "A new toy", "Stickers", "A video game"],
  },
  {
    id: "SS.IT.ECON.002",
    skillCode: "SS.ECON.GOODS",
    difficulty: -0.3,
    surface: "choice_grid",
    prompt: "Which is a service?",
    options: ["A haircut", "An apple", "A bicycle", "A backpack"],
  },
  {
    id: "SS.IT.ECON.003",
    skillCode: "SS.ECON.MARKET",
    difficulty: 0.6,
    surface: "choice_grid",
    prompt: "If demand goes up and supply stays the same, price tends to…",
    options: ["Go up", "Go down", "Stay the same", "Disappear"],
  },
  {
    id: "SS.IT.ECON.004",
    skillCode: "SS.ECON.SCARCITY",
    difficulty: 0.3,
    surface: "choice_grid",
    prompt: "Scarcity means…",
    options: ["Not enough to meet everyone's wants", "Free for everyone", "Too much of something", "Old and broken"],
  },
  {
    id: "SS.IT.ECON.005",
    skillCode: "SS.ECON.TRADE",
    difficulty: 0.7,
    surface: "choice_grid",
    prompt: "When a country sells goods to another country, that is called…",
    options: ["Exporting", "Importing", "Hoarding", "Donating"],
  },
  {
    id: "SS.IT.ECON.006",
    skillCode: "SS.ECON.MONEY",
    difficulty: 0.0,
    surface: "choice_grid",
    prompt: "What is a budget?",
    options: ["A plan for spending and saving", "A pile of coins", "A type of bank", "A wish list"],
  },
];
