import {
  pgTable,
  uuid,
  varchar,
  integer,
  boolean,
  date,
  jsonb,
  text,
  timestamp,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { learners } from "./learners.js";
import { tenants } from "./tenants.js";

/**
 * Phase 2 — calendar-driven weekly pacing.
 *
 * A learner's district/grade scope-&-sequence (generated by brain-svc) is
 * exploded into a dated, week-by-week plan aligned to a school calendar so the
 * tutor can serve the right topics each week and pause instruction over breaks.
 * brain-svc reads/writes these tables via raw SQL; this file is the schema +
 * migration source of truth (shared Postgres).
 */

export const schoolCalendars = pgTable(
  "school_calendars",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .references(() => tenants.id)
      .notNull(),
    // Calendars are learner-scoped in Phase 2 (a parent/teacher sets the term +
    // break dates for a learner). A district-shared calendar is a later phase.
    learnerId: uuid("learner_id")
      .references(() => learners.id, { onDelete: "cascade" })
      .notNull(),
    districtId: uuid("district_id"),
    name: varchar("name", { length: 255 }),
    academicYear: varchar("academic_year", { length: 16 }),
    timezone: varchar("timezone", { length: 64 }).notNull().default("America/Chicago"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("school_calendars_learner_id_idx").on(t.learnerId)],
);

export const schoolCalendarTerms = pgTable(
  "school_calendar_terms",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    calendarId: uuid("calendar_id")
      .references(() => schoolCalendars.id, { onDelete: "cascade" })
      .notNull(),
    termNumber: integer("term_number").notNull(),
    title: varchar("title", { length: 255 }),
    startDate: date("start_date").notNull(),
    endDate: date("end_date").notNull(),
  },
  (t) => [index("school_calendar_terms_calendar_id_idx").on(t.calendarId)],
);

export const schoolCalendarBreaks = pgTable(
  "school_calendar_breaks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    calendarId: uuid("calendar_id")
      .references(() => schoolCalendars.id, { onDelete: "cascade" })
      .notNull(),
    // "holiday" | "break" | "summer"
    kind: varchar("kind", { length: 16 }).notNull().default("break"),
    name: varchar("name", { length: 255 }),
    startDate: date("start_date").notNull(),
    endDate: date("end_date").notNull(),
  },
  (t) => [index("school_calendar_breaks_calendar_id_idx").on(t.calendarId)],
);

export const learnerPacingPlans = pgTable(
  "learner_pacing_plans",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .references(() => tenants.id)
      .notNull(),
    learnerId: uuid("learner_id")
      .references(() => learners.id, { onDelete: "cascade" })
      .notNull(),
    calendarId: uuid("calendar_id").references(() => schoolCalendars.id, {
      onDelete: "set null",
    }),
    subject: varchar("subject", { length: 64 }).notNull(),
    framework: varchar("framework", { length: 128 }),
    gradeLevel: varchar("grade_level", { length: 16 }),
    // "active" | "archived"
    status: varchar("status", { length: 16 }).notNull().default("active"),
    /**
     * Wave D (G6): parent opt-in to next-grade summer preparation. When
     * true and the current calendar break is kind "summer",
     * /pacing/current serves a summerBridge payload (closing-grade review
     * + next grade band's opening catalogue units) instead of plain
     * holiday prep.
     */
    optInSummerBridge: boolean("opt_in_summer_bridge").notNull().default(false),
    planStart: date("plan_start").notNull(),
    /** The raw scope-&-sequence the plan was exploded from (audit/regenerate). */
    sourceScopeSequence: jsonb("source_scope_sequence").default({}),
    pacingRationale: text("pacing_rationale"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("learner_pacing_plans_learner_id_idx").on(t.learnerId),
    index("learner_pacing_plans_subject_idx").on(t.subject),
    index("learner_pacing_plans_status_idx").on(t.status),
  ],
);

export const learnerPacingWeeks = pgTable(
  "learner_pacing_weeks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    pacingPlanId: uuid("pacing_plan_id")
      .references(() => learnerPacingPlans.id, { onDelete: "cascade" })
      .notNull(),
    weekIndex: integer("week_index").notNull(),
    weekStart: date("week_start").notNull(),
    weekEnd: date("week_end").notNull(),
    // "instruction" | "break" | "holiday_prep"
    kind: varchar("kind", { length: 16 }).notNull().default("instruction"),
    termNumber: integer("term_number"),
    unitTitle: varchar("unit_title", { length: 255 }),
    topics: jsonb("topics").default([]),
    standards: jsonb("standards").default([]),
    objectives: jsonb("objectives").default([]),
    vocabulary: jsonb("vocabulary").default([]),
    // "planned" | "active" | "done"
    status: varchar("status", { length: 16 }).notNull().default("planned"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("learner_pacing_weeks_plan_id_idx").on(t.pacingPlanId),
    index("learner_pacing_weeks_week_start_idx").on(t.weekStart),
  ],
);

export const schoolCalendarsRelations = relations(schoolCalendars, ({ one, many }) => ({
  learner: one(learners, {
    fields: [schoolCalendars.learnerId],
    references: [learners.id],
  }),
  terms: many(schoolCalendarTerms),
  breaks: many(schoolCalendarBreaks),
}));

export const learnerPacingPlansRelations = relations(learnerPacingPlans, ({ one, many }) => ({
  learner: one(learners, {
    fields: [learnerPacingPlans.learnerId],
    references: [learners.id],
  }),
  calendar: one(schoolCalendars, {
    fields: [learnerPacingPlans.calendarId],
    references: [schoolCalendars.id],
  }),
  weeks: many(learnerPacingWeeks),
}));

export const learnerPacingWeeksRelations = relations(learnerPacingWeeks, ({ one }) => ({
  plan: one(learnerPacingPlans, {
    fields: [learnerPacingWeeks.pacingPlanId],
    references: [learnerPacingPlans.id],
  }),
}));
