/**
 * Web-owned clinical persistence tables (Sprint 3).
 *
 * ADR 0015 — the canonical clinical records (IEP goals, therapist session
 * notes, caregiver observations) are owned by `services/family-svc` (mobile
 * already POSTs to /api/family/therapy-sessions, /observations,
 * /teacher-insights) and written through over REST
 * (lib/clinical/family-svc-client.ts). The ONE clinical artifact web-v2 owns
 * is the IEP **AI-draft review inbox**: an AI-generated IEP draft per learner
 * that moves through a review lifecycle (ai_draft → teacher_review →
 * admin_approved → active → archived). It is regenerated by upsert, so there
 * is one row per (learner, tenant).
 *
 * Conventions match web-domain.ts (TEXT ids, ISO-8601 TEXT timestamps, full
 * object in `data` JSONB). Tenant-scoped + RLS (migration 0082) — drafts are
 * read single-tenant by the reviewing teacher/admin, like web_iep_documents.
 */
import { pgTable, text, jsonb, index } from "drizzle-orm/pg-core";

export const webIepAiDrafts = pgTable(
  "web_iep_ai_drafts",
  {
    id: text("id").primaryKey(),
    learnerId: text("learner_id").notNull(),
    tenantId: text("tenant_id").notNull(),
    updatedAt: text("updated_at").notNull(),
    data: jsonb("data").notNull(),
  },
  (t) => ({ idx: index("web_iep_ai_drafts_idx").on(t.tenantId, t.learnerId) }),
);
