// Partially AUTO-GENERATED by `pnpm api:generate` (the `*-svc` modules)
// — do not edit those by hand. Regenerate after touching any service's
// route schemas.
//
// The `learning` sub-package below is hand-authored (Sprint 1: lesson
// player wiring) and pinned against drift by
// `__tests__/schema-pinning.test.ts`. React Query v5 hooks live in
// `./react` (separate entry point so non-React consumers don't pay the
// React import cost).
export * from "./learning/index.js";
export * as learning from "./learning/index.js";

export * as adminSvc from "./admin-svc.js";
export * as assessmentSvc from "./assessment-svc.js";
export * as billingSvc from "./billing-svc.js";
export * as commsSvc from "./comms-svc.js";
export * as engagementSvc from "./engagement-svc.js";
export * as familySvc from "./family-svc.js";
export * as i18nSvc from "./i18n-svc.js";
export * as identitySvc from "./identity-svc.js";
export * as integrationsSvc from "./integrations-svc.js";
export * as learningSvc from "./learning-svc.js";
export * as researchSvc from "./research-svc.js";
export * as statusPageSvc from "./status-page-svc.js";
export * as tutorSvc from "./tutor-svc.js";
